
var urls = [
    //'http://www.rong-chang.com/easykids/',
    //'http://www.rong-chang.com/children/',
    //'http://www.rong-chang.com/nnse/',
    //'http://www.rong-chang.com/ne/',
    'http://www.eslfast.com/easyread/index.html',
    //'http://www.eslfast.com/supereasy/index.htm',
    //'http://www.eslfast.com/easydialogs/dailylife.htm',
    //'http://www.eslfast.com/easydialogs/schoollife.htm',
    //'http://www.eslfast.com/easydialogs/transportation.htm',
    //'http://www.eslfast.com/easydialogs/entertainment.htm',
    //'http://www.eslfast.com/easydialogs/dating.htm',
    //'http://www.eslfast.com/easydialogs/restaurant.htm',
    //'http://www.eslfast.com/easydialogs/sports.htm',
    //'http://www.eslfast.com/easydialogs/safety.htm',
    //'http://www.eslfast.com/easydialogs/travel.htm',
    //'http://www.eslfast.com/easydialogs/jobs.htm',
    //'http://www.eslfast.com/easydialogs/food.htm',
    //'http://www.eslfast.com/easydialogs/shopping.htm',
    //'http://www.eslfast.com/easydialogs/housing.htm',
    //'http://www.eslfast.com/easydialogs/vote.htm',
    //'http://www.eslfast.com/easydialogs/health.htm',
];